### ISSUE TITLE
Suggestion - Allow temporary release of the com port

### ISSUE THREAD

**Issue by atuline** [nathandunk/BetterSerialPlotter#3]
Well, this is awesome, and I'll stop using the Arduino IDE for serial monitoring/plotting.

Am wondering if it's possible to temporarily release the com port, so I don't have to exit and restart 'Better Serial Plotter' each time I re-compile/upload to my board of choice.

**Comment by nathandunk** [comment]
Yeah, that should probably be there, so I will make this change. I normally run on Windows, in which there are normally several extra non-Arduino com ports available. I click on one of those, reupload, and then click back on the correct one. But now that you mention it, I realize that it doesn't work as well on mac/Linux because the ports are usually only taken by connected devices. @atuline, what OS are you using it on, just out of curiosity?

**Comment by nathandunk** [comment]
In [this release](https://github.com/nathandunk/BetterSerialPlotter/releases/tag/v0.1.1), I added a **Close Comport** button on the top row to suspend the connection. You can connect again by re-selecting the desired port in the Serial Port dropdown menu.

I am so glad that you are liking the app! How did you find it by the way? I mainly made it for my own use because I hated the arduino IDE's plotter and wanted something that just works, but with some extra features. 

I'm glad it is working will for you for FastLED purposes. I was actually using it with the neoPixel Library to react to audio input and found it really useful to be able to use several different plots to display different aspects of my program (1 plot for audio input, another for user adjustable parameters, and another for RGB outputs). Are you doing something similar?

Let me know if you have any more requests/suggestions! I am not aware of anyone else using it, so I haven't thought about making any improvements recently. I know that the program tends to crash every now and then when opening complicated config files, and I am planning on looking into why that is the case.

**Comment by atuline** [comment]
I found it via a WLED acquaintance, as I'm quite involved with sound reactivity. My github has several related repositories, most notably a sound reactive fork of WLED that's quite popular. It includes support for FFT, 2D matrices, and one of the contributors is working on an interpreter for i.

Anyways, I'm going to be passing it around the WLED Discord and Reddit forum as well as the FastLED Reddit forum. Hope you don't mind.

Oh, and thanks for the update!

**Comment by pipe01** [comment]
Just downloaded the app on linux and it works great (other than semi-frequent crashing haha). Could you release this version on linux, though? This seems very useful for development.

**Comment by josejoventino** [comment]
Olá, baixei o seu aplicativo e está muito bom, para melhorar ainda, seria possivel incluir uma linha para enviar comandos a serial, dessa forma poderiamos comutar blocos de dados, assim como na IDE do Arduino.
Gostei muito de seu plotter muito amigavel para excursionar o sinal, está de parabéns 
Obrigado por compartilhar ajuda bastante.

**Comment by pvo317** [comment]
хлам!
