### ISSUE TITLE
Compiling On Linux

### ISSUE THREAD

**Issue by ChSotiriou** [nathandunk/BetterSerialPlotter#4]
After a successful compilation on Arch Linux (Kernel 5.10.82-1-lts) I get the following assertion error.

```
BetterSerialPlotter: /home/christoss/Documents/fromSource/BetterSerialPlotter/build/_deps/mahi-gui-src/3rdparty/imgui/imgui.cpp:7784: void ImGuiStackSizes::CompareWithCurrentState(): Assertion `SizeOfIDStack == window->IDStack.Size && "PushID/PopID or TreeNode/TreePop Mismatch!"' failed.
fish: Job 1, './BetterSerialPlotter' terminated by signal SIGABRT (Abort)
```

The older precompiled version works just fine.

**Comment by nathandunk** [comment]
I think that is an extra check ImGui does when compiling in debug mode. If you are compiling in debug, could you by chance try compiling in release mode? That check is based on the ImGui library, and I spend a significant amount of time trying to fix this, but could not find where the problem was. While I will add this as something that I need to fix, I hope you can get it working in release mode.

**Comment by ChSotiriou** [comment]
Hello,

Yes I just compiled in release mode and runs just find. Great project.

Thank You  😀
